#!/bin/bash

sh /opt/liferay-portal-5.2.3/tomcat-6.0.18/bin/catalina.sh jpda start
#tail -f /opt/liferay-portal-5.2.3/tomcat-6.0.18/logs/catalina.out
multitail -cS apache -f /opt/liferay-portal-5.2.3/tomcat-6.0.18/logs/catalina.out
